import React from 'react'

function ConsoleAbout() {
  return (
    <section className='lg:ml-[15vw] pt-10 px-5 lg:h-[91.5vh]'>
      <h1 className='text-xl font-semibold mb-3'>About Me</h1>
      <div className='bg-white py-10 text-sm rounded-lg px-5 leading-10 overflow-y-scroll lg:h-[90%] h-[75vh]'>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam obcaecati corrupti omnis autem. Quisquam similique, quod accusantium in sed minima aperiam tenetur deleniti velit, corporis eveniet sit fugiat possimus nisi incidunt quos animi itaque doloremque porro. Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolores incidunt, assumenda impedit sunt facere similique eius ab nemo, magnam, nostrum quia. Nemo, laboriosam animi quas deleniti dicta at sint minus? Corporis tempore beatae vero pariatur quo harum alias quos, saepe commodi rem sequi porro fuga repellat quis dolorem corrupti labore aut nobis fugit placeat eveniet! Voluptate atque, ipsum dolorem minus quas eius voluptas ratione neque nulla aspernatur hic blanditiis quaerat alias odit sunt quasi ex magnam eaque adipisci, quis earum id cupiditate! Aliquam, tenetur odit laborum explicabo quos repudiandae eaque corporis error illum impedit reiciendis, iste, veritatis delectus at odio nihil obcaecati suscipit aspernatur sed accusantium dignissimos. Hic ipsum in perferendis assumenda nihil obcaecati laboriosam, sint beatae explicabo officia! Magni labore sit quisquam fuga repellendus impedit cupiditate perspiciatis minima nesciunt quis? Repudiandae sint quaerat officiis autem necessitatibus perferendis est excepturi cum vitae possimus voluptatum quos, impedit dolorem minus? Odio ducimus nisi rem adipisci error, velit, odit possimus libero tempore sed eum animi aliquam cumque soluta excepturi explicabo aspernatur commodi maxime. Asperiores ipsa, quisquam facere in fugit laudantium repudiandae impedit minus officia commodi laboriosam veniam nulla temporibus nobis blanditiis et molestias placeat quasi magnam dolore quia. Atque laudantium odio, natus ipsam beatae nesciunt unde provident ex commodi hic eligendi quam eveniet, animi tempore consequuntur repellendus dolorem accusantium deserunt fugit perspiciatis reiciendis quo amet vel. Iure aspernatur nihil, dolores recusandae fugit dignissimos cum ipsum, qui quos officiis perspiciatis exercitationem porro reprehenderit ipsam iste. Officiis earum doloremque ipsam quos odio alias ad et nostrum consequatur tempora atque quia nisi voluptas dolor, corrupti sequi quo. Corrupti, dolor. Beatae modi, ea ipsam deserunt velit at veniam culpa voluptates provident reprehenderit architecto magni facere delectus. Voluptas quisquam molestias, accusamus temporibus est distinctio provident ut blanditiis atque magni omnis maxime illo esse architecto mollitia consectetur? Unde, magni? Impedit distinctio saepe ipsam nisi similique, nesciunt rem rerum. Veniam dignissimos molestiae nihil nulla!</p>
      </div>
    </section>  
  )
}

export default ConsoleAbout